version: '2.1'

services:

  users-db:
    container_name: users-db
    build:
      context: ../flask-microservices-users/project/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build:
      context: ../flask-microservices-users
      dockerfile: Dockerfile-local
    volumes:
      - '../flask-microservices-users:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - users-service
      - web-service

  web-service:
    container_name: web-service
    build:
      context: ../flask-microservices-client
      dockerfile: Dockerfile-local
    volumes:
      - '../flask-microservices-client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

  swagger:
    container_name: swagger
    build:
      context: ../flask-microservices-swagger
    ports:
      - '8080:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/realpython/flask-microservices-swagger/master/swagger.json
    depends_on:
      users-service:
        condition: service_started

  eval-service:
    container_name: eval-service
    build:
      context: ../flask-microservices-eval
      dockerfile: Dockerfile-local
    volumes:
      - '../flask-microservices-eval:/usr/src/app'
    ports:
      - 5002:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - USERS_SERVICE_URL=http://users-service:5000
      - DATABASE_URL=postgres://postgres:postgres@eval-db:5432/eval_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@eval-db:5432/eval_test
    depends_on:
      users-service:
        condition: service_started
      eval-db:
        condition: service_healthy
    links:
      - users-service
      - eval-db

  eval-db:
    container_name: eval-db
    build:
      context: ../flask-microservices-eval/project/db
    ports:
        - 5436:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
